-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PMFS_AMAZONAS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PMFS_AMAZONAS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PMFS_AMAZONAS` DEFAULT CHARACTER SET utf8 ;
USE `PMFS_AMAZONAS` ;

-- -----------------------------------------------------
-- Table `PMFS_AMAZONAS`.`DETENTOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PMFS_AMAZONAS`.`DETENTOR` (
  `ID_DETENTOR` INT NOT NULL,
  `DOCUMENTO_DETENTOR` VARCHAR(45) NOT NULL,
  `TIPO_PESSOA_DETENTOR` VARCHAR(45) NOT NULL,
  `NOME_DETENTOR` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`ID_DETENTOR`),
  UNIQUE INDEX `DOCUMENTO_DETENTOR_UNIQUE` (`DOCUMENTO_DETENTOR` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PMFS_AMAZONAS`.`AMBIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PMFS_AMAZONAS`.`AMBIENTE` (
  `ID_AMBIENTE` INT NOT NULL AUTO_INCREMENT,
  `BIOMA` VARCHAR(100) NOT NULL,
  `CLIMA` VARCHAR(100) NOT NULL,
  `SOLO` TEXT NOT NULL,
  `FITOFISIONOMIA` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID_AMBIENTE`),
  UNIQUE INDEX `BIOMA_UNIQUE` (`BIOMA` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PMFS_AMAZONAS`.`SILVICULTURA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PMFS_AMAZONAS`.`SILVICULTURA` (
  `ID_SILVICULTURA` INT NOT NULL AUTO_INCREMENT,
  `METODO_EXTRACAO` VARCHAR(150) NOT NULL,
  `SISTEMA_SILVICULTURAL` VARCHAR(100) NOT NULL,
  `CICLO_CORTE` DECIMAL(5,2) NOT NULL,
  `AREA_TOTAL_PROPRIEDADE` DECIMAL(15,2) NOT NULL,
  `AREA_MANEJO_FLORESTAL` DECIMAL(15,2) NOT NULL,
  `AREA_EFETIVO_MANEJO` DECIMAL(15,2) NOT NULL,
  `CAPACIDADE_PRODUTIVA` DECIMAL(10,2) NOT NULL,
  `ESTIMATIVA_PRODUTIVA_ANUAL` DECIMAL(10,2) NOT NULL,
  `INTENSIDADE_CORTE` DECIMAL(5,2) NOT NULL,
  `TIPO_VOLUME` VARCHAR(45) NOT NULL,
  `FORMULA_VOLUME` TEXT NOT NULL,
  PRIMARY KEY (`ID_SILVICULTURA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PMFS_AMAZONAS`.`EMPREENDIMENTO_TIPO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PMFS_AMAZONAS`.`EMPREENDIMENTO_TIPO` (
  `ID_EMPREENDIMENTO_TIPO` INT NOT NULL AUTO_INCREMENT,
  `TIPO_DE_EMPREENDIMENTO` VARCHAR(100) NOT NULL,
  `NATUREZA_JURIDICA` VARCHAR(100) NOT NULL,
  `COMPETENCIA_DA_AVALIACAO` VARCHAR(100) NOT NULL,
  `ORGAO_AMBIENTAL_RESP_ANALISE` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`ID_EMPREENDIMENTO_TIPO`),
  UNIQUE INDEX `TIPO_DE_EMPREENDIMENTO_UNIQUE` (`TIPO_DE_EMPREENDIMENTO` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PMFS_AMAZONAS`.`PROJETO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PMFS_AMAZONAS`.`PROJETO` (
  `NRO_REGISTRO` INT NOT NULL,
  `DATA_DE_EMISSAO` DATE NULL DEFAULT NULL,
  `NRO_AUTORIZACAO` BIGINT NULL,
  `NUMERO_ORIGINAL` INT NOT NULL,
  `ANO_AUTORIZACAO` YEAR NULL,
  `DESCRICAO_AUTORIZACAO` TEXT NULL,
  `DATA_DE_VALIDADE` DATE NULL,
  `ID_DETENTOR` INT NOT NULL,
  `ID_EMPREENDIMENTO` INT NOT NULL,
  `ID_AMBIENTE` INT NOT NULL,
  `ID_SILVICULTURA` INT NOT NULL,
  `SITUACAO` VARCHAR(100) NULL,
  `DATA_SITUACAO` DATE NULL,
  `ULTIMO_TRAMITE` VARCHAR(100) NULL,
  `DATA_DO_TRAMITE` DATE NULL,
  `ULTIMA_ATUALIZACAO_RELATORIO` DATE NULL,
  PRIMARY KEY (`NRO_REGISTRO`),
  INDEX `ID_DETENTOR_idx` (`ID_DETENTOR` ASC) VISIBLE,
  INDEX `ID_AMBIENTE_idx` (`ID_AMBIENTE` ASC) VISIBLE,
  INDEX `ID_SILVICULTURA_idx` (`ID_SILVICULTURA` ASC) VISIBLE,
  INDEX `ID_EMPREENDIMENTO_idx` (`ID_EMPREENDIMENTO` ASC) VISIBLE,
  CONSTRAINT `ID_DETENTOR`
    FOREIGN KEY (`ID_DETENTOR`)
    REFERENCES `PMFS_AMAZONAS`.`DETENTOR` (`ID_DETENTOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_AMBIENTE`
    FOREIGN KEY (`ID_AMBIENTE`)
    REFERENCES `PMFS_AMAZONAS`.`AMBIENTE` (`ID_AMBIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_SILVICULTURA`
    FOREIGN KEY (`ID_SILVICULTURA`)
    REFERENCES `PMFS_AMAZONAS`.`SILVICULTURA` (`ID_SILVICULTURA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_EMPREENDIMENTO`
    FOREIGN KEY (`ID_EMPREENDIMENTO`)
    REFERENCES `PMFS_AMAZONAS`.`EMPREENDIMENTO_TIPO` (`ID_EMPREENDIMENTO_TIPO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PMFS_AMAZONAS`.`ESTADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PMFS_AMAZONAS`.`ESTADO` (
  `ID_ESTADO` INT NOT NULL,
  `UF` VARCHAR(45) NOT NULL,
  `NOME_ESTADO_REGISTRO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UF`, `NOME_ESTADO_REGISTRO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PMFS_AMAZONAS`.`MUNICIPIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PMFS_AMAZONAS`.`MUNICIPIO` (
  `ID_MUNICIPIO` INT NOT NULL AUTO_INCREMENT,
  `NOME_MUNICIPIO` VARCHAR(100) NOT NULL,
  `UF` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_MUNICIPIO`),
  UNIQUE INDEX `NOME_MUNICIPIO_UNIQUE` (`NOME_MUNICIPIO` ASC) VISIBLE,
  INDEX `UF_idx` (`UF` ASC) VISIBLE,
  CONSTRAINT `UF`
    FOREIGN KEY (`UF`)
    REFERENCES `PMFS_AMAZONAS`.`ESTADO` (`UF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PMFS_AMAZONAS`.`IMOVEL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PMFS_AMAZONAS`.`IMOVEL` (
  `ID_IMOVEL` INT NOT NULL AUTO_INCREMENT,
  `NRO_CAR_IMOVEL_RURAL` VARCHAR(45) NOT NULL,
  `IMOVEL_RURAL_VINCULADO` VARCHAR(150) NOT NULL,
  `NOME_EMPREENDIMENTO_VINC` VARCHAR(150) NOT NULL,
  `LATITUDE_EMPREENDIMENTO` FLOAT NOT NULL,
  `ID_MUNICIPIO` INT NOT NULL,
  PRIMARY KEY (`ID_IMOVEL`),
  UNIQUE INDEX `NRO_CAR_IMOVEL_RURAL_UNIQUE` (`NRO_CAR_IMOVEL_RURAL` ASC) VISIBLE,
  INDEX `ID_MUNICIPIO _idx` (`ID_MUNICIPIO` ASC) VISIBLE,
  CONSTRAINT `ID_MUNICIPIO `
    FOREIGN KEY (`ID_MUNICIPIO`)
    REFERENCES `PMFS_AMAZONAS`.`MUNICIPIO` (`ID_MUNICIPIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PMFS_AMAZONAS`.`RESPONSAVEL_TECNICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PMFS_AMAZONAS`.`RESPONSAVEL_TECNICO` (
  `ID_RESPONSAVEL_TECNICO` INT NOT NULL AUTO_INCREMENT,
  `NRO_ART` VARCHAR(45) NOT NULL,
  `NOME_DO_RT` VARCHAR(100) NOT NULL,
  `ATIVIDADE_RT` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID_RESPONSAVEL_TECNICO`),
  UNIQUE INDEX `NRO_ART_UNIQUE` (`NRO_ART` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PMFS_AMAZONAS`.`PMFS_MODALIDADE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PMFS_AMAZONAS`.`PMFS_MODALIDADE` (
  `ID_PMFS_MODALIDADE` INT NOT NULL AUTO_INCREMENT,
  `MODALIDADE_PMFS` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID_PMFS_MODALIDADE`),
  UNIQUE INDEX `MODALIDADE_PMFS_UNIQUE` (`MODALIDADE_PMFS` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PMFS_AMAZONAS`.`PROJETO_PMFS_MODALIDADE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PMFS_AMAZONAS`.`PROJETO_PMFS_MODALIDADE` (
  `ID_PROJETO_MODALIDADE` INT NOT NULL AUTO_INCREMENT,
  `NRO_REGISTRO` INT NULL,
  `ID_PMFS_MODALIDADE` INT NULL,
  PRIMARY KEY (`ID_PROJETO_MODALIDADE`),
  INDEX `NRO_REGISTRO_idx` (`NRO_REGISTRO` ASC) VISIBLE,
  INDEX `ID_PMFS_MODALIDADE_idx` (`ID_PMFS_MODALIDADE` ASC) VISIBLE,
  CONSTRAINT `FK_PMFS_NRO_REGISTRO`
    FOREIGN KEY (`NRO_REGISTRO`)
    REFERENCES `PMFS_AMAZONAS`.`PROJETO` (`NRO_REGISTRO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_PMFS_MODALIDADE`
    FOREIGN KEY (`ID_PMFS_MODALIDADE`)
    REFERENCES `PMFS_AMAZONAS`.`PMFS_MODALIDADE` (`ID_PMFS_MODALIDADE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PMFS_AMAZONAS`.`PROJETO_IMOVEL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PMFS_AMAZONAS`.`PROJETO_IMOVEL` (
  `ID_PROJETO_IMOVEL` INT NOT NULL AUTO_INCREMENT,
  `NRO_REGISTRO` INT NULL,
  `ID_IMOVEL` INT NULL,
  PRIMARY KEY (`ID_PROJETO_IMOVEL`),
  INDEX `NRO_REGISTRO_idx` (`NRO_REGISTRO` ASC) VISIBLE,
  INDEX `ID_IMOVEL_idx` (`ID_IMOVEL` ASC) VISIBLE,
  CONSTRAINT `FK_IMOVEL_NRO_REGISTRO`
    FOREIGN KEY (`NRO_REGISTRO`)
    REFERENCES `PMFS_AMAZONAS`.`PROJETO` (`NRO_REGISTRO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_IMOVEL`
    FOREIGN KEY (`ID_IMOVEL`)
    REFERENCES `PMFS_AMAZONAS`.`IMOVEL` (`ID_IMOVEL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PMFS_AMAZONAS`.`PROJETO_RESPONSAVEL_TECNICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PMFS_AMAZONAS`.`PROJETO_RESPONSAVEL_TECNICO` (
  `ID_PROJETO_RT` INT NOT NULL,
  `NRO_REGISTRO` INT NULL,
  `ID_RESPONSAVEL_TECNICO` INT NULL,
  PRIMARY KEY (`ID_PROJETO_RT`),
  INDEX `NRO_REGISTRO_idx` (`NRO_REGISTRO` ASC) VISIBLE,
  INDEX `ID_RESPONSAVEL_TECNICO_idx` (`ID_RESPONSAVEL_TECNICO` ASC) VISIBLE,
  CONSTRAINT `FK_RT_NRO_REGISTRO`
    FOREIGN KEY (`NRO_REGISTRO`)
    REFERENCES `PMFS_AMAZONAS`.`PROJETO` (`NRO_REGISTRO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_RESPONSAVEL_TECNICO`
    FOREIGN KEY (`ID_RESPONSAVEL_TECNICO`)
    REFERENCES `PMFS_AMAZONAS`.`RESPONSAVEL_TECNICO` (`ID_RESPONSAVEL_TECNICO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
